import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";

const VERDICTS: Record<string, { label: string; tone: string; description: string }> = {
  NATURAL_ORIGINAL: { label: "NATURAL / ORIGINAL", tone: "natural", description: "Evidence is consistent with a naturally captured, original image with no detected significant manipulation." },
  ORIGINAL_EDITED: { label: "ORIGINAL — EDITED", tone: "edited", description: "Evidence is consistent with a camera-originated image, with editing or recompression indicators detected." },
  AI_ALTERED: { label: "AI-ALTERED", tone: "ai", description: "Evidence indicates an original or camera-originated image has been modified with generative AI." },
  AI_GENERATED: { label: "AI-GENERATED", tone: "ai", description: "Evidence indicates the image was synthetically generated by an AI model." },
  MANIPULATED: { label: "MANIPULATED", tone: "manipulated", description: "Evidence indicates significant image manipulation, but AI involvement is not established." },
  AUTHENTICITY_UNDETERMINED: { label: "UNDETERMINED", tone: "unknown", description: "Available evidence is insufficient to determine the image's origin or integrity." },
  INSUFFICIENT_EVIDENCE: { label: "UNDETERMINED", tone: "unknown", description: "Available evidence is insufficient to determine the image's origin or integrity." },
};

function pretty(value: unknown) {
  return String(value ?? "—").replaceAll("_", " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function detectorState(runs: any[] | null | undefined, names: string[]) {
  const found = (runs ?? []).filter((r) => names.some((n) => String(r.detector_name ?? "").toLowerCase().includes(n)));
  if (!found.length) return "Not run";
  return found.some((r) => r.score !== null) ? "Measured" : "Recorded";
}

export default async function ForensicAnalysisPage({ params }: { params: Promise<{ analysisId: string }> }) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { analysisId } = await params;
  const { data: analysis } = await supabase.from("analyses").select("*,media(*)").eq("id", analysisId).maybeSingle();
  if (!analysis) notFound();

  const [{ data: evidence }, { data: provenance }, { data: artifacts }, { data: detectorRuns }, { data: fusionRuns }] = await Promise.all([
    supabase.from("evidence_items").select("*").eq("analysis_id", analysisId).order("created_at"),
    supabase.from("provenance_records").select("*").eq("analysis_id", analysisId).order("created_at"),
    supabase.from("forensic_artifacts").select("*").eq("analysis_id", analysisId).order("created_at"),
    supabase.from("detector_runs").select("*").eq("analysis_id", analysisId).order("created_at"),
    supabase.from("fusion_runs").select("*").eq("analysis_id", analysisId).order("created_at", { ascending: false }),
  ]);

  const classification = fusionRuns?.[0]?.classification ?? analysis.assessment ?? "AUTHENTICITY_UNDETERMINED";
  const verdict = VERDICTS[classification] ?? { label: pretty(classification), tone: "unknown", description: "The current evidence fusion result is not mapped to a standard KIOREL verdict." };
  const displayStatus = pretty(analysis.status);
  const neuralEnabled = (detectorRuns ?? []).some((r) => /trufor|dire|neural|ai/i.test(String(r.detector_name)));
  const c2pa = (provenance ?? []).find((p) => String(p.source).toLowerCase() === "c2pa");
  const quantitativeDetector = (detectorRuns ?? []).some((r) => r.score_semantics === "manipulation_probability" && r.score !== null);

  return (
    <main className="dashboard-shell forensic-workstation">
      <header className="dashboard-nav workstation-nav">
        <Link className="brand" href="/dashboard">KIOREL</Link>
        <div className="dashboard-actions">
          <Link className="button secondary" href="/dashboard/forensics">Investigations</Link>
          <Link className="button primary" href="/dashboard/forensics/upload">New analysis</Link>
        </div>
      </header>

      <section className="workstation">
        <div className="workstation-head">
          <div>
            <span className="mono dashboard-eyebrow">MEDIA AUTHENTICITY WORKSTATION / {analysis.pipeline_version}</span>
            <h1>{analysis.media?.filename ?? "Media investigation"}</h1>
            <p>One verdict, multiple evidence layers. KIOREL separates provenance, natural-image forensics, manipulation analysis, and generative-AI evidence before producing the final assessment.</p>
          </div>
          <div className="workstation-status"><span className="status-dot" /> {displayStatus}</div>
        </div>

        <section className={"verdict-panel " + verdict.tone}>
          <div className="verdict-copy">
            <span className="mono">01 / FINAL INTEGRITY VERDICT</span>
            <div className="verdict-label">{verdict.label}</div>
            <p>{verdict.description}</p>
          </div>
          <div className="verdict-meta">
            <div><span>Confidence</span><strong>{analysis.confidence !== null ? Math.round(Number(analysis.confidence) * 100) + "%" : "Not available"}</strong></div>
            <div><span>Evidence items</span><strong>{evidence?.length ?? 0}</strong></div>
            <div><span>Neural analysis</span><strong>{neuralEnabled ? "Active" : "Not enabled"}</strong></div>
          </div>
        </section>

        <div className="verdict-note">
          <strong>How to read this result</strong>
          <span>The verdict is an evidence-fusion outcome, not a claim that any single forensic signal proves authenticity or AI generation.</span>
        </div>

        <section className="evidence-overview">
          <div className="section-label">02 / EVIDENCE COVERAGE</div>
          <div className="evidence-matrix">
            <div className="coverage-card"><span>PROVENANCE</span><strong>{c2pa?.status === "manifest_found" ? "Credential found" : "No C2PA credential"}</strong><small>Content Credentials / metadata</small></div>
            <div className="coverage-card"><span>NATURAL FORENSICS</span><strong>{detectorState(detectorRuns, ["ela", "fft", "dct", "noise", "cfa"])}</strong><small>Compression, frequency, noise & CFA</small></div>
            <div className="coverage-card"><span>MANIPULATION</span><strong>{quantitativeDetector ? "Quantitative detector" : "Diagnostic only"}</strong><small>Evidence of local or global alteration</small></div>
            <div className="coverage-card"><span>GENERATIVE AI</span><strong>{neuralEnabled ? "Detector active" : "Not enabled"}</strong><small>AI generation / AI alteration models</small></div>
          </div>
        </section>

        <div className="workstation-grid">
          <article className="workstation-panel">
            <div className="panel-heading"><span>03 / PROVENANCE</span><h2>Origin & file history</h2></div>
            {provenance?.length ? provenance.map((item: any) => (
              <div className="evidence-row" key={item.id}><div><strong>{pretty(item.source)}</strong><small>{item.status}</small></div><span>{item.status === "manifest_found" ? "SUPPORTED" : "INSPECTED"}</span></div>
            )) : <p className="empty-note">No provenance results yet.</p>}
          </article>

          <article className="workstation-panel">
            <div className="panel-heading"><span>04 / FORENSIC SIGNALS</span><h2>Natural-image diagnostics</h2></div>
            {detectorRuns?.length ? detectorRuns.map((run: any) => (
              <div className="evidence-row" key={run.id}><div><strong>{pretty(run.detector_name)}</strong><small>{run.score !== null ? "Signal " + Number(run.score).toPrecision(6) : "No numeric score"}</small></div><span>MEASURED</span></div>
            )) : <p className="empty-note">Signal detectors will appear as the worker completes.</p>}
            <p className="technical-note">ELA, FFT, DCT, noise-residual and CFA values are diagnostic measurements. They are not AI probabilities.</p>
          </article>

          <article className="workstation-panel">
            <div className="panel-heading"><span>05 / AI & ALTERATION</span><h2>Generative evidence</h2></div>
            <div className="assessment-row"><span>AI generation</span><strong>{neuralEnabled ? "Analyzed" : "Not determined"}</strong></div>
            <div className="assessment-row"><span>AI alteration</span><strong>{neuralEnabled ? "Analyzed" : "Not determined"}</strong></div>
            <div className="assessment-row"><span>Manipulation</span><strong>{quantitativeDetector ? "Detector evidence available" : "Diagnostic evidence only"}</strong></div>
            <p className="technical-note">{neuralEnabled ? "Neural detector output is available to the fusion layer." : "KIOREL will not infer an AI verdict from ELA/FFT/DCT/CFA alone."}</p>
          </article>

          <article className="workstation-panel">
            <div className="panel-heading"><span>06 / EVIDENCE LEDGER</span><h2>Traceable findings</h2></div>
            {evidence?.length ? evidence.map((item: any) => (
              <div className="evidence-row" key={item.id}><div><strong>{pretty(item.detector)}</strong><small>{item.finding}</small></div><span>LOGGED</span></div>
            )) : <p className="empty-note">Evidence will appear as analysis stages complete.</p>}
          </article>

          <article className="workstation-panel">
            <div className="panel-heading"><span>07 / FORENSIC ARTIFACTS</span><h2>Diagnostic maps</h2></div>
            {artifacts?.length ? <div className="artifact-list">{artifacts.map((item: any) => <Link className="artifact-link" href={"/api/forensics/artifacts/" + item.id} target="_blank" key={item.id}><span>{pretty(item.artifact_type)}</span><b>OPEN ↗</b></Link>)}</div> : <p className="empty-note">No artifacts available yet.</p>}
          </article>

          <article className="workstation-panel">
            <div className="panel-heading"><span>08 / FILE IDENTITY</span><h2>Media fingerprint</h2></div>
            <div className="fingerprint"><span>SHA-256</span><code>{analysis.media?.sha256 ?? "—"}</code></div>
            <div className="fingerprint"><span>PIPELINE</span><code>{analysis.pipeline_version}</code></div>
          </article>
        </div>
      </section>
    </main>
  );
}
